-- QUERY ORIGINAL

UPDATE FREQ 
SET FREQ.CAMPO_13 = 'PN', 
    FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (CELULAR DO PROFESSOR COM DATA ERRADA): ' + FREQ.CAMPO_14, 
    FREQ.CAMPO_22 = convert(varchar(10),DT_REGISTRO,120)
--SELECT FREQ.CAMPO_13, FREQ.CAMPO_14, FREQ.CAMPO_22 
FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ WITH(NOLOCK)
WHERE FREQ.ID_PROGRAMA = 80  
AND FREQ.ID_PARTICAO = 3
AND FREQ.ID_LEIAUTE_ARQUIVO = 11
AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11
AND FREQ.CAMPO_13 = 'ER'
AND FREQ.CAMPO_14 = 'A Data da aula não pode ser uma data futura.'
AND FREQ.DT_REGISTRO BETWEEN CONVERT(DATE, DATEADD(MM,-2,GETDATE())) AND CONVERT(DATE, DATEADD(MM,+2,GETDATE()))
AND DATEDIFF(DAY,DT_REGISTRO,CAMPO_22) = 1
--SET STATISTICS IO OFF

-- QUERY ALTERADA

UPDATE FREQ 
SET FREQ.CAMPO_13 = 'PN', 
    FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (CELULAR DO PROFESSOR COM DATA ERRADA): ' + FREQ.CAMPO_14, 
    FREQ.CAMPO_22 = DT_REGISTRO_0
--SELECT FREQ.CAMPO_13, FREQ.CAMPO_14, FREQ.CAMPO_22 
FROM DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ WITH(NOLOCK)
WHERE FREQ.ID_PROGRAMA = 80  
AND FREQ.ID_PARTICAO = 3
AND FREQ.ID_LEIAUTE_ARQUIVO = 11
AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11
AND FREQ.CAMPO_13 = 'ER'
AND FREQ.CAMPO_14 = 'A Data da aula não pode ser uma data futura.'
AND FREQ.DT_REGISTRO BETWEEN DT_REGISTRO_MINOR_2 AND DT_REGISTRO_MAJOR_2
AND DT_REGISTRO_DATEDIFF = 1
OPTION (RECOMPILE, QUERYTRACEON 8649, MAXDOP 10)
--SET STATISTICS IO OFF

-- CREATE PROCEDURE

ALTER PROCEDURE USP_UPDATE_TB_RESULTADO_DIARIO_DE_CLASSE_CELULAR_PROFESSOR
WITH EXECUTE AS 'cibelle'
AS
BEGIN
	UPDATE FREQ 
	SET FREQ.CAMPO_13 = 'PN', 
		FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (CELULAR DO PROFESSOR COM DATA ERRADA): ' + FREQ.CAMPO_14, 
		FREQ.CAMPO_22 = DT_REGISTRO_0
	--SELECT FREQ.CAMPO_13, FREQ.CAMPO_14, FREQ.CAMPO_22 
	FROM DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ WITH(NOLOCK)
	WHERE FREQ.ID_PROGRAMA = 80  
	AND FREQ.ID_PARTICAO = 3
	AND FREQ.ID_LEIAUTE_ARQUIVO = 11
	AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11
	AND FREQ.CAMPO_13 = 'ER'
	AND FREQ.CAMPO_14 = 'A Data da aula não pode ser uma data futura.'
	AND FREQ.DT_REGISTRO BETWEEN DT_REGISTRO_MINOR_2 AND DT_REGISTRO_MAJOR_2
	AND DT_REGISTRO_DATEDIFF = 1
	OPTION (RECOMPILE, QUERYTRACEON 8649, MAXDOP 10)
END


EXEC USP_UPDATE_TB_RESULTADO_DIARIO_DE_CLASSE_CELULAR_PROFESSOR

---------------------------------------------------------------------------

-- QUERY ORIGINAL
-- 00:02:01
UPDATE FREQ 
SET FREQ.CAMPO_13 = 'PR', 
    FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (DATA INVÁLIDA (DATA FUTURA): ' + FREQ.CAMPO_14 
-- SELECT FREQ.CAMPO_13, FREQ.CAMPO_14
FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ
WHERE FREQ.ID_PROGRAMA = 80  
AND FREQ.ID_PARTICAO = 3 
AND FREQ.ID_LEIAUTE_ARQUIVO = 11 
AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11 
AND FREQ.CAMPO_13 = 'ER' 
AND FREQ.CAMPO_14 = 'A Data da aula não pode ser uma data futura.' 
AND FREQ.DT_REGISTRO BETWEEN CONVERT(DATE, DATEADD(MM,-2,GETDATE())) AND CONVERT(DATE, DATEADD(MM,+2,GETDATE()))
AND DATEDIFF(DAY, DT_REGISTRO, CAMPO_22) > 1

-- QUERY ALTERADA
-- 00:00:01
UPDATE FREQ 
SET FREQ.CAMPO_13 = 'PR', 
    FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (DATA INVÁLIDA (DATA FUTURA): ' + FREQ.CAMPO_14 
-- SELECT FREQ.CAMPO_13, FREQ.CAMPO_14
FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ
WHERE FREQ.ID_PROGRAMA = 80  
AND FREQ.ID_PARTICAO = 3 
AND FREQ.ID_LEIAUTE_ARQUIVO = 11 
AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11 
AND FREQ.CAMPO_13 = 'ER' 
AND FREQ.CAMPO_14 = 'A Data da aula não pode ser uma data futura.' 
AND FREQ.DT_REGISTRO BETWEEN  DT_REGISTRO_MINOR_2 AND DT_REGISTRO_MAJOR_2
AND  DT_REGISTRO_DATEDIFF > 1
OPTION (RECOMPILE, QUERYTRACEON 8649, MAXDOP 10)

-- CREATE PROCEDURE
ALTER PROCEDURE USP_UPDATE_TB_RESULTADO_DIARIO_DE_CLASSE_DATA_INVALIDA
WITH EXECUTE AS 'cibelle'
AS
BEGIN
	UPDATE FREQ 
	SET FREQ.CAMPO_13 = 'PR', 
		FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (DATA INVÁLIDA (DATA FUTURA): ' + FREQ.CAMPO_14 
	-- SELECT FREQ.CAMPO_13, FREQ.CAMPO_14
	FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ
	WHERE FREQ.ID_PROGRAMA = 80  
	AND FREQ.ID_PARTICAO = 3 
	AND FREQ.ID_LEIAUTE_ARQUIVO = 11 
	AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11 
	AND FREQ.CAMPO_13 = 'ER' 
	AND FREQ.CAMPO_14 = 'A Data da aula não pode ser uma data futura.' 
	AND FREQ.DT_REGISTRO BETWEEN  DT_REGISTRO_MINOR_2 AND DT_REGISTRO_MAJOR_2
	AND  DT_REGISTRO_DATEDIFF > 1
	OPTION (RECOMPILE, QUERYTRACEON 8649, MAXDOP 10)
END

EXEC USP_UPDATE_TB_RESULTADO_DIARIO_DE_CLASSE_DATA_INVALIDA

-----------------------------------------------------------------

-- QUERY ORIGINAL
-- 00:01:35
UPDATE FREQ 
SET FREQ.CAMPO_13 = 'PR', 
    FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (TURMA NÃO ENCONTRADA): ' + FREQ.CAMPO_14 
-- SELECT FREQ.CAMPO_13, FREQ.CAMPO_14
FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ
WHERE FREQ.ID_PROGRAMA = 80 
  AND FREQ.ID_PARTICAO = 3
  AND FREQ.ID_LEIAUTE_ARQUIVO = 11
  AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11
  AND FREQ.CAMPO_13 = 'ER'
  AND FREQ.CAMPO_14 = 'Turma informada não existe.'
  AND FREQ.DT_REGISTRO BETWEEN '2018-10-01' AND '2018-12-01'

-- QUERY ALTERADA
-- 00:00:00
UPDATE FREQ 
SET FREQ.CAMPO_13 = 'PR', 
    FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (TURMA NÃO ENCONTRADA): ' + FREQ.CAMPO_14 
--SELECT FREQ.CAMPO_13, FREQ.CAMPO_14
FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ
WHERE FREQ.ID_PROGRAMA = 80 
  AND FREQ.ID_PARTICAO = 3
  AND FREQ.ID_LEIAUTE_ARQUIVO = 11
  AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11
  AND FREQ.CAMPO_13 = 'ER'
  AND FREQ.CAMPO_14 = 'Turma informada não existe.'
  AND FREQ.DT_REGISTRO BETWEEN '2018-10-01' AND '2018-12-01'
OPTION (RECOMPILE, QUERYTRACEON 8649, maxdop 10)

-- CREATE PROCEDURE
ALTER PROCEDURE USP_UPDATE_TB_RESULTADO_DIARIO_DE_CLASSE_TURMA_NAO_ENCONTRADA  @DT_INICIO DATE, @DT_FIM DATE
WITH EXECUTE AS 'cibelle'
AS
BEGIN
	UPDATE FREQ 
	SET FREQ.CAMPO_13 = 'PR', 
		FREQ.CAMPO_14 = 'ERRO NÃO TRATADO (TURMA NÃO ENCONTRADA): ' + FREQ.CAMPO_14 
	--SELECT FREQ.CAMPO_13, FREQ.CAMPO_14
	FROM REPOSITORIO_TEMPLATE.DBO.TB_RESULTADO_DIARIO_DE_CLASSE FREQ
	WHERE FREQ.ID_PROGRAMA = 80 
	AND FREQ.ID_PARTICAO = 3
	AND FREQ.ID_LEIAUTE_ARQUIVO = 11
	AND FREQ.ID_LEIAUTE_ARQUIVO_CLASSIFICACAO = 11
	AND FREQ.CAMPO_13 = 'ER'
	AND FREQ.CAMPO_14 = 'Turma informada não existe.'
	AND FREQ.DT_REGISTRO BETWEEN @DT_INICIO AND @DT_FIM
	OPTION (RECOMPILE, QUERYTRACEON 8649, MAXDOP 10)
END


EXEC USP_UPDATE_TB_RESULTADO_DIARIO_DE_CLASSE_TURMA_NAO_ENCONTRADA '2018-10-01', '2018-12-01'