-- indice duplicado

USE [SIA_CPD]
GO

drop INDEX [IXNC_TB_UNIDADE_012] ON [dbo].[TB_UNIDADE]

/****** Object:  Index [IXNC_TB_UNIDADE_012]    Script Date: 23/11/2018 16:14:26 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_UNIDADE_012] ON [dbo].[TB_UNIDADE]
(
	[ID_PROJETO] ASC,
	[ID_UNIDADE] ASC,
	[ID_AGREGADO] ASC,
	[ID_TIPO_UNIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_UNIDADE_06]    Script Date: 23/11/2018 16:14:32 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_UNIDADE_06] ON [dbo].[TB_UNIDADE]
(
	[ID_PROJETO] ASC,
	[ID_UNIDADE] ASC,
	[ID_AGREGADO] ASC,
	[ID_TIPO_UNIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


drop iNDEX [IXNC_TB_UNIDADE_011] ON [dbo].[TB_UNIDADE]


USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_UNIDADE_05]    Script Date: 23/11/2018 16:07:17 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_UNIDADE_05] ON [dbo].[TB_UNIDADE]
(
	[ID_PROJETO] ASC,
	[ID_UNIDADE] ASC,
	[ID_UNIDADE_SUPERIOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO




USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_UNIDADE_011]    Script Date: 23/11/2018 16:12:19 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_UNIDADE_011] ON [dbo].[TB_UNIDADE]
(
	[ID_PROJETO] ASC,
	[ID_UNIDADE] ASC,
	[ID_UNIDADE_SUPERIOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


USE [SIA_CPD]
GO

DROP INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_07] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]

EXEC SP_RENAME N'DBO.TB_REQ_DISTRIBUICAO_GATEWAY.IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06', N'IXFT_TB_REQ_DISTRIBUICAO_GATEWAY_01', N'INDEX'



/****** Object:  Index [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06]    Script Date: 23/11/2018 10:49:33 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[DC_SITUACAO] ASC,
	[DT_EVALUATE_TELEFORM] ASC,
	[DT_REQ_DISTRIBUICAO] ASC
)
WHERE ([DT_EVALUATE_TELEFORM] IS NULL AND [DC_SITUACAO]='DISTRIBUIDO')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_07]    Script Date: 23/11/2018 10:49:44 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_07] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[DC_SITUACAO] ASC,
	[DT_COMMIT_TELEFORM] ASC,
	[DT_REQ_DISTRIBUICAO] ASC
)
WHERE ([DC_SITUACAO]='DISTRIBUIDO' AND [DT_COMMIT_TELEFORM] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


-- modificacao indice

/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([DC_SITUACAO],[DT_COMMIT_TELEFORM],[DT_REQ_DISTRIBUICAO])

GO
*/


 /*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([DC_SITUACAO],[DT_COMMIT_TELEFORM],[DT_REQ_DISTRIBUICAO])

GO
*/

-- antes

USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06]    Script Date: 23/11/2018 11:01:39 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[DC_SITUACAO] ASC,
	[DT_EVALUATE_TELEFORM] ASC,
	[DT_REQ_DISTRIBUICAO] ASC
)
WHERE ([DT_EVALUATE_TELEFORM] IS NULL AND [DC_SITUACAO]='DISTRIBUIDO')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO

-- depois

/****** Object:  Index [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06]    Script Date: 23/11/2018 10:49:33 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[DC_SITUACAO] ASC,
	[DT_REQ_DISTRIBUICAO] ASC,
	DT_COMMIT_TELEFORM asc
)
include ([DT_EVALUATE_TELEFORM])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


---------------------

/*
Missing Index Details from SQLQuery12.sql - 10.0.10.21.SIA_CPD (TELEFORM\sqlserversrvsia (350))
The Query Processor estimates that implementing the following index could improve the query cost by 99.7995%.
*/

/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([CD_MASCARA],[VL_SENSIBILIDADE],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM])
GO
*/


/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([CD_MASCARA_TELEFORM],[VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM])
GO
*/



------------------------


SELECT ID_REQ_DISTRIBUICAO, DC_CAMINHO_COMPLETO, NM_IMAGEM, DC_LOTE_SCANNER, CD_MASCARA 
FROM TB_REQ_DISTRIBUICAO_GATEWAY  with (forceseek,INDEX(IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_01))
WHERE NU_LOTE_GATEWAY=2383514 AND NM_IMAGEM='52405404070298_0472.jpg' AND VL_SENSIBILIDADE=130



USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_01]    Script Date: 23/11/2018 10:24:25 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_01] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[NU_LOTE_GATEWAY] ASC,
	[NM_IMAGEM] ASC
)
INCLUDE ( 	[ID_REQ_DISTRIBUICAO],
	[DC_CAMINHO_COMPLETO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO




/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([CD_MASCARA_TELEFORM],[VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM])
GO
*/

USE [SIA_CPD]
GO

/****** Object:  Index [IX_REQ_DISTRIBUICAO_GATEWAY]    Script Date: 22/11/2018 15:22:44 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_01] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[NU_LOTE_GATEWAY] ASC,
	[NM_IMAGEM] ASC
)
INCLUDE ( 	
      ID_REQ_DISTRIBUICAO
	, DC_CAMINHO_COMPLETO
	, DC_LOTE_SCANNER
	, CD_MASCARA
	, VL_SENSIBILIDADE
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, 
	DROP_EXISTING = ON, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO



--46 571 240
SELECT * FROM SYSINDEXES WHERE NAME = 'PK_TB_REQ_DISTRIBUICAO_GATEWAY'


--declare @1 int
--,@2 int
--,@3 int
--,@4 int
--UPDATE [TB_REQ_DISTRIBUICAO_GATEWAY] 
--set [CD_MASCARA_TELEFORM] = @1,[NU_LOTE_TELEFORM] = @2,[DT_EVALUATE_TELEFORM] = @3  
--WHERE [ID_REQ_DISTRIBUICAO]=@4



DECLARE @P0 INT
,@P1 INT
select instituica0_.NM_INSTITUICAO as col_0_0_, instituica0_.ID_INSTITUICAO_TIPO as col_1_0_, instituico1_.ID_PROJETO as col_2_0_, instituica0_.DC_CAMINHO as col_3_0_, instituica0_.ID_INSTITUICAO as col_4_0_, instituica0_.DC_HIERARQUIA as col_5_0_ 
from TB_INSTITUICAO instituica0_ 
inner join TB_INSTITUICAO_PROJETO instituico1_ on instituica0_.ID_INSTITUICAO=instituico1_.ID_INSTITUICAO 
where instituica0_.ID_INSTITUICAO_TIPO=@P0 and instituico1_.ID_PROJETO=@P1 and instituica0_.FL_ATIVO='true' 
order by instituica0_.NM_INSTITUICAO           




-- SOLUCAO


-- 1 606 525
SELECT * FROM SYSINDEXES WHERE NAME = 'PK_TB_INSTITUICAO'




--USE [SIA_CPD]
--GO

--/****** Object:  Index [IXNC_TB_INSTITUICAO_09]    Script Date: 22/11/2018 15:40:46 ******/
--CREATE NONCLUSTERED INDEX IXNC_TB_INSTITUICAO_09 ON [dbo].[TB_INSTITUICAO]
--(
--	[FL_ATIVO] ASC,
--	[ID_INSTITUICAO_TIPO] ASC,
--	[ID_INSTITUICAO] ASC,
--	[NM_INSTITUICAO] ASC,
--	[DC_HIERARQUIA] ASC,
--	[DC_HIERARQUIA_TIPO] ASC
--)
--INCLUDE ([DC_CAMINHO])
--WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
--GO



/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_INSTITUICAO] ([FL_ATIVO],[ID_INSTITUICAO_TIPO])
INCLUDE ([ID_INSTITUICAO],[NM_INSTITUICAO],[DC_CAMINHO],[DC_HIERARQUIA])
GO     
*/


DECLARE @P1 varchar(100)
SELECT ID_MASCARA, CD_PROJETO, VL_SENSIBILIDADE 
FROM TB_BASE_PLANEJADA --with(index(IXNC_TB_BASE_PLANEJADA_01))
 WHERE NU_SEQUENCIAL= @P1




-- 40 427 252
SELECT * FROM SYSINDEXES WHERE NAME = 'PK_TB_BASE_PLANEJADA'


-- SOLUCAO

--USE [SIA_CPD]
--GO

--/****** Object:  Index [IXNC_TB_BASE_PLANEJADA_01]    Script Date: 22/11/2018 15:45:52 ******/
--CREATE NONCLUSTERED INDEX [IXNC_TB_BASE_PLANEJADA_01] ON [dbo].[TB_BASE_PLANEJADA]
--(
--	[NU_SEQUENCIAL] ASC
--)
--INCLUDE (ID_MASCARA, CD_PROJETO, VL_SENSIBILIDADE)
--WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
--GO


USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_BASE_PLANEJADA_02]    Script Date: 22/11/2018 17:29:32 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_BASE_PLANEJADA_02] ON [dbo].[TB_BASE_PLANEJADA]
(
	[ID_MASCARA] ASC,
	[NU_SEQUENCIAL] ASC
)
INCLUDE ( 	[ID_BASE_PLANEJADA], VL_SENSIBILIDADE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, 
SORT_IN_TEMPDB = OFF, DROP_EXISTING = on, ONLINE = on, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO








-- A SOLUCAO ACIMA CORRUGE O KEY LOOKUP
DECLARE 
	 @P1 varchar(100)
	,@P2 varchar(100)
SELECT ID_BASE_PLANEJADA FROM TB_BASE_PLANEJADA WHERE NU_SEQUENCIAL=@P1 AND ID_MASCARA=@P2









SELECT DC_MODELO_SCANNER,VL_SENSIBILIDADE,DC_CAMINHO_COMPLETO,nu_lote_teleform, DC_LOTE_SCANNER,substring(nm_imagem,1,
charindex('.', nm_imagem)-1) as ID_IMAGEM, convert(varchar,dt_commit_teleform,103) + ' '+ convert(varchar,dt_commit_teleform,108) as dt_commit_teleform, cd_mascara
 FROM TB_rEQ_DISTRIBUICAO_GATEWAY 
WHERE NM_IMAGEM='52400678230407_0410.jpg' AND NU_LOTE_TELEFORM=543441 AND CD_MASCARA NOT IN ('TELEFORM_NONFORM')


SELECT DC_MODELO_SCANNER,VL_SENSIBILIDADE,DC_CAMINHO_COMPLETO,nu_lote_teleform, DC_LOTE_SCANNER,substring(nm_imagem,1,charindex('.', nm_imagem)-1) as ID_IMAGEM, convert(varchar,dt_commit_teleform,103) + ' '+ convert(varchar,dt_commit_teleform,108) as dt_commit_teleform, cd_mascara 
FROM TB_rEQ_DISTRIBUICAO_GATEWAY WHERE NM_IMAGEM='52301270080225_0306.jpg' AND NU_LOTE_TELEFORM=544364 AND CD_MASCARA NOT IN ('TELEFORM_NONFORM')

-- SOLUCAO 
USE [SIA_CPD]
GO

/****** OBJECT:  INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_04]    SCRIPT DATE: 22/11/2018 15:58:57 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_04] ON [DBO].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[NM_IMAGEM] ASC,
	[NU_LOTE_TELEFORM] ASC
)
INCLUDE (CD_MASCARA, DC_MODELO_SCANNER,VL_SENSIBILIDADE,DC_CAMINHO_COMPLETO, DC_LOTE_SCANNER, DT_COMMIT_TELEFORM)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = on, ONLINE = on, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO




select count(*) as TOTAL , dc_scanner_origem, NM_USUARIO_SCANNER  FROM TB_REQ_DISTRIBUICAO_GATEWAY NOLOCK  WHERE cast(DT_REQ_DISTRIBUICAO as date) = '2018-11-22' 
AND CD_MASCARA_TELEFORM = 'TELEFORM_NONFORM' 
AND CD_MASCARA not in  ('TELEFORM_NONFORM') 
AND VL_SENSIBILIDADE=130 
group by dc_scanner_origem, NM_USUARIO_SCANNER order by 1 desc 


select count(*) as TOTAL , dc_scanner_origem, NM_USUARIO_SCANNER  FROM TB_REQ_DISTRIBUICAO_GATEWAY NOLOCK  
WHERE cast(DT_REQ_DISTRIBUICAO as date) = '2018-11-23' 
AND CD_MASCARA in  ('MASKNR') 
AND VL_SENSIBILIDADE=130 
group by dc_scanner_origem , NM_USUARIO_SCANNER  order by 1 desc 


-- SOLUCAO

USE [SIA_CPD]
GO

/****** Object:  Index [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_05]    Script Date: 22/11/2018 16:03:13 ******/
CREATE NONCLUSTERED INDEX [IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_05] ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY]
(
	[DT_EVALUATE_TELEFORM] ASC,
	[VL_SENSIBILIDADE] ASC,
	[DT_REQ_DISTRIBUICAO] ASC
)
INCLUDE (
[CD_MASCARA_TELEFORM],[CD_MASCARA], [NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO



/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([CD_MASCARA_TELEFORM],[VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM])
GO
*/



-- SUGESTAO 
/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] 
([CD_MASCARA_TELEFORM],[VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM])
GO
*/


DECLARE
	@P1 INT,
	@P2 INT,
	@P3 INT,
	@P4 INT,
	@P5 INT,
	@P6 INT,
	@P7 INT,
	@P8 INT
INSERT INTO TB_IMAGEM_DIGITALIZADA (CD_MASCARA ,DT_DIGITALIZADA ,NM_IMAGEM          ,DC_CAMINHO_COMPLETO   ,DC_LOTE_SCANNER      ,NM_USUARIO_SCANNER   ,DC_SCANNER_ORIGEM, DC_MODELO_SCANNER, FL_CONFIRMADA)
 VALUES (@P1, @P2, @P3, @P4, @P5, @P6, @P7, @P8,0) 



 SELECT COUNT(*) AS TOTAL FROM TB_REQ_DISTRIBUICAO_GATEWAY nolock WHERE dt_req_distribuicao>= getdate() -1 and DC_SITUACAO = 'DISTRIBUIDO' AND dt_commit_teleform is null

  SELECT COUNT(*) AS TOTAL FROM TB_REQ_DISTRIBUICAO_GATEWAY --WITH(INDEX(IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_06)) 
  WHERE dt_req_distribuicao>= getdate() -1 and DC_SITUACAO = 'DISTRIBUIDO' AND dt_commit_teleform is null


 /*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([DC_SITUACAO],[DT_COMMIT_TELEFORM],[DT_REQ_DISTRIBUICAO])

GO
*/


SELECT COUNT(*) AS TOTAL FROM TB_REQ_DISTRIBUICAO_GATEWAY NOLOCK WHERE DT_REQ_DISTRIBUICAO >= getdate() -1  AND DT_EVALUATE_TELEFORM IS NULL AND DC_SITUACAO='DISTRIBUIDO'



declare @p0 int
select top 2 controlequ0_.ID_CONTROLE_QUALIDADE_ARMAZENAMENTO as ID1_4_, controlequ0_.DT_FIM as DT2_4_, controlequ0_.DT_INICIO as DT3_4_, controlequ0_.ID_UNIDADE as ID4_4_, controlequ0_.ID_USUARIO_FIM as ID5_4_, controlequ0_.ID_USUARIO_INICIO as ID6_4_ from TB_CONTROLE_QUALIDADE_ARMAZENAMENTO controlequ0_ 
where controlequ0_.ID_UNIDADE=@P0        



----------------
-- 5 seg
-- caiu para 0 seg
SELECT COUNT(*) AS TOTAL , DC_SCANNER_ORIGEM, NM_USUARIO_SCANNER  
FROM TB_REQ_DISTRIBUICAO_GATEWAY NOLOCK 
 WHERE CAST(DT_REQ_DISTRIBUICAO AS DATE) = '2018-11-23' 
 AND CD_MASCARA_TELEFORM = 'TELEFORM_NONFORM' 
 AND CD_MASCARA NOT IN  ('TELEFORM_NONFORM') 
 AND VL_SENSIBILIDADE=130 
 GROUP BY DC_SCANNER_ORIGEM, NM_USUARIO_SCANNER ORDER BY 1 DESC 


-- solucao 

USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_07
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([CD_MASCARA_TELEFORM],[VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = off, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO


---------

SELECT COUNT(*) as total, NM_USUARIO_SCANNER, datediff(minute,MIN(DT_DIGITALIZADA),MAX(DT_DIGITALIZADA)) as totalminutos,
count(*)/datediff(minute,MIN(DT_DIGITALIZADA),MAX(DT_DIGITALIZADA)) * 60 as mediahora  
FROM TB_REQ_DISTRIBUICAO_GATEWAY NOLOCK  
WHERE cast(DT_REQ_DISTRIBUICAO as date) = '2018-11-23' 
AND CD_MASCARA NOT IN ('TELEFORM_NONFORM') 
AND NM_USUARIO_SCANNER NOT IN ('daniel','REPOSITORIO') 
AND VL_SENSIBILIDADE=130 GROUP BY NM_USUARIO_SCANNER

-- sugestao de indice sql

/*
USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO],[NM_USUARIO_SCANNER])
INCLUDE ([DT_DIGITALIZADA])
GO
*/


USE [SIA_CPD]
GO
CREATE NONCLUSTERED INDEX IXNC_TB_REQ_DISTRIBUICAO_GATEWAY_07
ON [dbo].[TB_REQ_DISTRIBUICAO_GATEWAY] ([CD_MASCARA_TELEFORM],[VL_SENSIBILIDADE],[CD_MASCARA],[DT_REQ_DISTRIBUICAO])
INCLUDE ([NM_USUARIO_SCANNER],[DC_SCANNER_ORIGEM], DT_DIGITALIZADA)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = on, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [FG_INDEX_SIA_CPD]
GO