--drop table #TMPWHO3

WAITFOR DELAY '00:00:05';
SET DEADLOCK_PRIORITY HIGH
IF OBJECT_ID('TEMPDB..#TMPWHO3') IS NOT NULL DROP TABLE #TMPWHO3
CREATE TABLE #TMPWHO3
(SPID INT, BLKBY INT, ELAPSEDMS INT, CPU BIGINT, IOREADS BIGINT, IOWRITES BIGINT,EXECUTIONS INT, COMMANDTYPE VARCHAR(255), 
LASTWAITTYPE VARCHAR(255), OBJECTNAME VARCHAR(255), SQLSTATEMENT VARCHAR(MAX), STATUS VARCHAR(255), 
LOGIN VARCHAR(255), HOST VARCHAR(255), DBNAME VARCHAR(255), STARTTIME DATETIME, PROTOCOL VARCHAR(100), 
TRANSACTION_ISOLATION VARCHAR(100), CONNECTIONWRITES INT, CONNECTIONREADS INT, CLIENTADRESS VARCHAR(100), 
AUTHENTICATION VARCHAR(50), DATETIMESNAPSHOT DATETIME)
INSERT INTO #TMPWHO3
EXEC SP_WHO3
DECLARE @SPID INT
DECLARE @TSTRING VARCHAR(15)
DECLARE @GETSPID CURSOR
SET @GETSPID =   CURSOR FOR
SELECT SPID
FROM #TMPWHO3
WHERE DBNAME LIKE 'SISLAME_%' AND SQLSTATEMENT LIKE ' SELECT  	MIN(cfda.DT_AULA)  FROM  	VW_CONSULTA_FREQUENCIA_DIARIA_ALUNO cfda  WHERE ID_DIVISAO = @P0 AND%'
OPEN @GETSPID
FETCH NEXT FROM @GETSPID INTO @SPID
WHILE @@FETCH_STATUS = 0
BEGIN
SET @TSTRING = 'KILL ' + CAST(@SPID AS VARCHAR(5))
EXEC(@TSTRING)
FETCH NEXT FROM @GETSPID INTO @SPID
END
CLOSE @GETSPID
DEALLOCATE @GETSPID
DROP TABLE #TMPWHO3
GO 10000  


