-- verificar quais objectos estao com a propriedade ansi_nulls habilidata

USE TEMPDB
GO


SET ANSI_NULLS ON
GO
CREATE PROCEDURE DBO.FOO1
AS
SELECT 1
GO
SET ANSI_NULLS OFF
GO

CREATE PROCEDURE DBO.FOO2 AS
SELECT 1
GO

SELECT NAME = OBJECT_NAME(OBJECT_ID), USES_ANSI_NULLS
FROM SYS.SQL_MODULES
WHERE OBJECT_NAME(object_id) IN ('FOO1', 'FOO2')
GO


DROP PROCEDURE FOO1, FOO2




SELECT NAME = OBJECT_NAME(M.OBJECT_ID), USES_ANSI_NULLS, O.TYPE_DESC--, *
FROM SYS.SQL_MODULES M
INNER JOIN SYS.OBJECTS O ON M.OBJECT_ID = O.OBJECT_ID
WHERE 
--OBJECT_NAME(OBJECT_ID) IN ('FOO1', 'FOO2')
USES_ANSI_NULLS = 0
ORDER BY 1
GO


-- https://subhrosaha.wordpress.com/2012/01/21/use-of-set-ansi_nulls-onoff-in-sql-server-stored-procedures/